name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc, clang]
        python-version: ['3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: python -m pip install numpy pytest

    - name: Configure CMake
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: PYTHONPATH=build:$PYTHONPATH pytest -v test
      
